# Request
GET / HTTP/1.1
Host: hydra.newpaltz.edu/hello.txt

#####

#Response
HTTP/1.1 400 Bad Request
Date: Mon, 06 Mar 2023 18:09:59 GMT
Server: Apache/2.4.54 (Ubuntu)
Content-Length: 446
Connection: close
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
Reason: You're speaking plain HTTP to an SSL-enabled server port.<br />
 Instead use the HTTPS scheme to access this URL, please.<br />
</p>
<hr>
<address>Apache/2.4.54 (Ubuntu) Server at hydra.newpaltz.edu Port 80</address>
</body></html>

printf 'GET / HTTP/1.1\r\nHost: hydra.newpaltz.edu/hello.txt\r\n\r\n'