[package]
name = "table_merger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
mysql = "23.0.1"
regex = "1.7.1"
serde = "1.0.159"