aaa                                                  a
bbb                                                  a
^                                                    a
aaaab                                                a
abaaa                                                a
aabaa                                                a
aaaba                                                a
aaaab                                                a
abababab                                             a
abab                                                 a
aaaaaaaaabbb                                         a
ababbbbbbb                                           a
a                                                    r
aa                                                   r
aab                                                  r
aaabb                                                r
bbaaa                                                r
ababababa                                            r
abababaa                                             r
