aa                                                   a
bb                                                   a
aaaa                                                 a
bbbb                                                 a
abab                                                 a
baba                                                 a
aaa                                                  a
bbb                                                  a
aabaa                                                a
bbabb                                                a
abbbbbbbbbbbbab                                      a
bbabababb                                            a
^                                                    r
a                                                    r
b                                                    r
aab                                                  r
bba                                                  r
abb                                                  r
aaaaaaaaaaaab                                        r
abba                                                 r
aaa                                                  a
bbb                                                  a
^                                                    a
aaaab                                                a
abaaa                                                a
aabaa                                                a
aaaba                                                a
aaaab                                                a
abababab                                             a
abab                                                 a
aaaaaaaaabbb                                         a
ababbbbbbb                                           a
a                                                    r
aa                                                   r
aab                                                  r
aaabb                                                r
bbaaa                                                r
ababababa                                            r
abababaa                                             r