^                                                         a
a                                                         a
b                                                         a
c                                                         a
d                                                         a
ab                                                        a
ac                                                        a
ad                                                        a
bc                                                        a
bd                                                        a
cd                                                        a
abc                                                       a
abd                                                       a
acd                                                       a
bcd                                                       a
abcd                                                      a
aacc                                                      a
bbdd                                                      a
aa                                                        a
bb                                                        a
cc                                                        a
dd                                                        a
ba                                                        r
ca                                                        r
da                                                        r
cb                                                        r
db                                                        r
dc                                                        r
abcda                                                     r
abcccdc                                                   r
bcb                                                       r
dda                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           r
