c                                                    a
bcc                                                  a
bccc                                                 a
bbbccccccc                                           a
^                                                    r
bc                                                   r
bbcc                                                 r
bccb                                                 r
ccccccb                                              r
