^                                                    a
ad                                                   a
aadd                                                 a
bc                                                   a
bbcc                                                 a
abcd                                                 a
aabcdd                                               a
abbccd                                               a
aaaaaddddd                                           a
bbbbbccccc                                           a
aaabbbbccccddd                                       a
adbc                                                 r
bcda                                                 r
abcda                                                r
abcdd                                                r
abcdc                                                r
abcda                                                r
bca                                                  r
bcd                                                  r
aabbccddd                                            r
aabbccd                                              r
baabcd                                               r
abcdd                                                r
abccd                                                r
abbcd                                                r
aabcd                                                r
aabbccd                                              r
aabbcdd                                              r
aabccdd                                              r
abbccdd                                              r                                                        r
