^                                                    a
abb                                                  a
aabbbb                                               a
aaabbbb                                              r
a                                                    r
ab                                                   r
abbb                                                 r
aabbb                                                r
babb                                                 r
abba                                                 r
