aaaaabbbbbb                                           a
bbbbbaaaaaa                                           a
aaaaaabb                                              a
ab                                                    r
aa                                                    a
babbb                                                 a
aabbb                                                 a
aaabb                                                 a
ababa                                                 a
abb                                                   a
aaaab                                                 a
abbbbb                                                a
abbabbabb                                             a
^                                                     r
ab                                                    r
aabb                                                  r
ba                                                    r
bbaa                                                  r
abba                                                  r
baab                                                  r
abab                                                  r
