c                                                    a
ac                                                   a
bc                                                   a
aaaac                                                a
bbbbc                                                a
^                                                    r
abc                                                  r
aca                                                  r
bca                                                  r
bcb                                                  r
