^             r
aa            r
bb            r
aaaa          r
abab          r
baba          r
bbbb          r
aabaab        r
a             a
b             a
aabbb         a
aaabb         a
abba          a
abbaba        a
