/* Generated By:JavaCC: Do not edit this line. S2jConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface S2jConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PRINTLN = 6;
  /** RegularExpression Id. */
  int PRINT = 7;
  /** RegularExpression Id. */
  int UNSIGNED = 8;
  /** RegularExpression Id. */
  int ID = 9;
  /** RegularExpression Id. */
  int ASSIGN = 10;
  /** RegularExpression Id. */
  int SEMICOLON = 11;
  /** RegularExpression Id. */
  int LEFTPAREN = 12;
  /** RegularExpression Id. */
  int RIGHTPAREN = 13;
  /** RegularExpression Id. */
  int LEFTCURL = 14;
  /** RegularExpression Id. */
  int RIGHTCURL = 15;
  /** RegularExpression Id. */
  int PLUS = 16;
  /** RegularExpression Id. */
  int MINUS = 17;
  /** RegularExpression Id. */
  int TIMES = 18;
  /** RegularExpression Id. */
  int DIV = 19;
  /** RegularExpression Id. */
  int ERROR = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "<token of kind 5>",
    "\"println\"",
    "\"print\"",
    "<UNSIGNED>",
    "<ID>",
    "\"=\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<ERROR>",
  };

}
