bccb           a
bcccb          a
bccccb         a
ccbcc          a
ccbbcc         a
cccccbbcc      a
cbcccb         a
ccccbcc        a
b              r
bb             r
bbb            r
c              r
cc             r
bcbc           r
bcc            r
cbb            r
