aa                                                   a
bb                                                   a
aaaa                                                 a
bbbb                                                 a
abab                                                 a
baba                                                 a
aaa                                                  a
bbb                                                  a
aabaa                                                a
bbabb                                                a
abbbbbbbbbbbbab                                      a
bbabababb                                            a
^                                                    r
a                                                    r
b                                                    r
aab                                                  r
bba                                                  r
abb                                                  r
aaaaaaaaaaaab                                        r
abba                                                 r
