^                                                           a
aaa                                                         a
aaaaaa                                                      a
bbb                                                         a
bbbbbb                                                      a
aaabbb                                                      a
bbbaaa                                                      a
bababa                                                      a
ababab                                                      a
abababababab                                                a
aabbaabbaabb                                                a
aabbbbbba                                                   a
a                                                           r
aa                                                          r
b                                                           r
bb                                                          r
aaab                                                        r
aaabb                                                       r
bbba                                                        r
bbbaa                                                       r
bbaaa                                                       r
aabbb                                                       r
abababb                                                     r
aaabbba                                                     r
