aba                                                        a
aaaaba                                                     a
bbbaba                                                     a
abababa                                                    a
ababa                                                      a
abab                                                       r
a                                                          r
ab                                                         r
abab                                                       r
ababab                                                     r
^                                                          r
abaabaabab                                                 r
bba                                                        r
aaa                                                        r
aab                                                        r
abb                                                        r
baa                                                        r
bab                                                        r
bba                                                        r
bbb                                                        r
