a                                                         a
aaa                                                       a
aaaaa                                                     a
bba                                                       a
abb                                                       a
abbbb                                                     a
ababa                                                     a
^                                                         r
ab                                                        r
aabb                                                      r
abab                                                      r
babab                                                     r
