^                                                    a
ac                                                   a
ab                                                   a
aabc                                                 a
aaabbb                                               a
aaaccc                                               a
aaaabbcc                                             a
aabcc                                                r
aabbc                                                r
abcc                                                 r
bc                                                   r
bb                                                   r
cc                                                   r
